### ISSUE TITLE
feature-request: IAM-User optional

### ISSUE THREAD

**Issue by jneumann90** [opensourceelectrolux/aws-cost-exporter#11]
Hey there,

I'd love to try the exporter in one of your environments, but as most companies do not allow the usage of AWS IAM-User for permission management, rather than using IAM-Roles:

Would it be possible to make the usage of IAM-User optional? And if no credentials are provided, let boto3 just rely on the EC2-Instance-Role instead?

**Comment by gluckzhang** [comment]
Hi @jneumann90, thanks for reaching out. This sounds like a great idea. I think we can follow the [default behavior of the AWS SDK](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials) to determine the AWS credentials.

I will take a look at this later when I have some time. Please also feel free to contribute if you are interested in the implementation :)

**Comment by gluckzhang** [comment]
This is now supported by `v1.0.5`: https://github.com/opensourceelectrolux/aws-cost-exporter/releases/tag/v1.0.5 Thank you both @jneumann90 @rpabano ! 🎉
